### ISSUE TITLE
error: ‘remove’ is not a member of ‘std’

### ISSUE THREAD

**Issue by tianyuandu** [buresu/DBSCAN#1]
The error message:
    DBSCAN-master/dbscan.cpp:43:21: error: ‘remove’ is not a member of ‘std’
         seeds.erase(std::remove(seeds.begin(), seeds.end(), p), seeds.end());

I think you forgot to add "#include <algorithm>".
After that your code could be run successfully.

**Comment by buresu** [comment]
Thank you for your reporting.
I added include at commit f8cbdc910d8d22e19256bee8152c298a9a02571d and tested it on msvc 2015.
